server:
  port: 30000

spring:
  application:
    name: hello-provider-boot
  cloud:
    nacos:
      discovery:
        server-addr: nacos-headless:8848
        enabled: true
        instance-enable: true
      username: nacos
      password: nacos
    sentinel:
      datasource:
        dsl:
          nacos:
            server-addr: nacos-headless:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
    endpoints:
        web:
        exposure:
            include: '*'
    endpoint:
      health:
        show-details: ALWAYS

