server:
  port: 0

spring:
  application:
    name: hello-provider-boot
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.186.135:8848
        enabled: true
        instance-enable: true
      username: nacos
      password: nacos

management:
    endpoints:
        web:
        exposure:
            include: '*'
    endpoint:
      health:
        show-details: ALWAYS

